name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - main
jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Declare some variables
        shell: bash
        run:
          echo "sha_short=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ github.repository_owner }}/python-poc:${{env.sha_short}}