name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Declare some variables
        shell: bash
        run:
          echo "sha_short=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ github.repository_owner }}/python-poc:${{env.sha_short}}
    outputs:
      commit_id: ${{env.sha_short}}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Clone the repo
        uses: action/checkout@v3
      - name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-poc/values.yaml
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit {{needs.ci.outputs.commit_id}}'
      - name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --grpc-web
          argocd app sync python-poc